apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: category-service
  name: category-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: category-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/hska-vis-legacy-local-dev-net: "true"
        io.kompose.service: category-service
    spec:
      containers:
        - env:
            - name: MYSQL_HOST
              value: web-shop-db-image
            - name: PRODUCT_ENDPOINT
              value: product-service
          image: stumpfalexdockerka/hska-vis-legacy-category-service
          name: category-service
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
